/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class TelaSistema extends javax.swing.JFrame {
    Leituras leitura = new Leituras();
    Leituras leitura2= new Leituras();
    Leituras leitura3= new Leituras();
    
    Integer contador = 0;

    /**
     * Creates new form TelaSistema
     */
    public TelaSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pgbPrimeira = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pgbSegunda = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pgbTerceira = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        btnObter = new javax.swing.JButton();
        lblminimo = new javax.swing.JLabel();
        lblmaximo = new javax.swing.JLabel();
        lblmedia = new javax.swing.JLabel();
        lblValorMinimo = new javax.swing.JLabel();
        lblValorMaximo = new javax.swing.JLabel();
        lblValormedio = new javax.swing.JLabel();
        lblValorMinimo1 = new javax.swing.JLabel();
        lblValorMaximo1 = new javax.swing.JLabel();
        lblValormedio1 = new javax.swing.JLabel();
        lblminimo1 = new javax.swing.JLabel();
        lblmaximo1 = new javax.swing.JLabel();
        lblmedia1 = new javax.swing.JLabel();
        lblValorMinimo2 = new javax.swing.JLabel();
        lblValorMaximo2 = new javax.swing.JLabel();
        lblValormedio2 = new javax.swing.JLabel();
        lblminimo3 = new javax.swing.JLabel();
        lblmaximo3 = new javax.swing.JLabel();
        lblmedia3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CPU");

        pgbPrimeira.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("%De utilização");

        jLabel3.setText("100%");

        jLabel4.setText("0%");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Memória");

        pgbSegunda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("%De utilização");

        jLabel7.setText("100%");

        jLabel8.setText("0%");

        jLabel9.setText("100%");

        jLabel10.setText("0%");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Disco");

        pgbTerceira.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setText("%De utilização");

        btnObter.setText("Obter dados");
        btnObter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObterActionPerformed(evt);
            }
        });

        lblminimo.setText("Minimo:");

        lblmaximo.setText("Maximo:");

        lblmedia.setText("Médio:");

        lblValorMinimo.setText("0");

        lblValorMaximo.setText("0");

        lblValormedio.setText("0");

        lblValorMinimo1.setText("0");

        lblValorMaximo1.setText("0");

        lblValormedio1.setText("0");

        lblminimo1.setText("Minimo:");

        lblmaximo1.setText("Maximo:");

        lblmedia1.setText("Médio:");

        lblValorMinimo2.setText("0");

        lblValorMaximo2.setText("0");

        lblValormedio2.setText("0");

        lblminimo3.setText("Minimo:");

        lblmaximo3.setText("Maximo:");

        lblmedia3.setText("Médio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(151, 151, 151)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(pgbTerceira, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(151, 151, 151)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(pgbSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(pgbPrimeira, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblminimo3)
                        .addGap(5, 5, 5)
                        .addComponent(lblValorMinimo2)
                        .addGap(18, 18, 18)
                        .addComponent(lblmaximo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorMaximo2)
                        .addGap(34, 34, 34)
                        .addComponent(lblmedia3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValormedio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnObter)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblminimo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorMinimo1)
                                .addGap(18, 18, 18)
                                .addComponent(lblmaximo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorMaximo1)
                                .addGap(34, 34, 34)
                                .addComponent(lblmedia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValormedio1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblminimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorMinimo)
                                .addGap(18, 18, 18)
                                .addComponent(lblmaximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorMaximo)
                                .addGap(34, 34, 34)
                                .addComponent(lblmedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValormedio)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgbPrimeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblminimo)
                        .addComponent(lblmaximo)
                        .addComponent(lblmedia)
                        .addComponent(lblValorMinimo)
                        .addComponent(lblValorMaximo)
                        .addComponent(lblValormedio)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pgbSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblminimo1)
                            .addComponent(lblValorMinimo1)
                            .addComponent(lblmaximo1)
                            .addComponent(lblValorMaximo1)
                            .addComponent(lblmedia1)
                            .addComponent(lblValormedio1))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbTerceira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblminimo3)
                        .addComponent(lblmaximo3)
                        .addComponent(lblmedia3)
                        .addComponent(lblValorMinimo2)
                        .addComponent(lblValorMaximo2)
                        .addComponent(lblValormedio2)))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObterActionPerformed
        leitura.sortearValor();
        
        contador++;
        
         pgbPrimeira.setStringPainted(true);
         pgbPrimeira.setString(leitura.valorAleatorio.toString());
         pgbPrimeira.setValue(leitura.valorAleatorio);
         
         lblValorMinimo.setText(leitura.valorMinimo.toString());
         lblValorMaximo.setText(leitura.valorMaximo.toString());
         
         lblValormedio.setText(String.format("%.2f",leitura.media/contador));
         //======================================================================//
         leitura2.sortearValor();
         
         pgbSegunda.setStringPainted(true);
         pgbSegunda.setString(leitura2.valorAleatorio.toString());
         pgbSegunda.setValue(leitura2.valorAleatorio);
         
         lblValorMinimo1.setText(leitura2.valorMinimo.toString());
         lblValorMaximo1.setText(leitura2.valorMaximo.toString());
         
         lblValormedio1.setText(String.format("%.2f",leitura2.media/contador));
         //====================================================================//
         leitura3.sortearValor();
         
         pgbTerceira.setStringPainted(true);
         pgbTerceira.setString(leitura3.valorAleatorio.toString());
         pgbTerceira.setValue(leitura3.valorAleatorio);
         
         lblValorMinimo2.setText(leitura3.valorMinimo.toString());
         lblValorMaximo2.setText(leitura3.valorMaximo.toString());
         
         lblValormedio2.setText(String.format("%.2f",leitura3.media/contador));
         
    }//GEN-LAST:event_btnObterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblValorMaximo;
    private javax.swing.JLabel lblValorMaximo1;
    private javax.swing.JLabel lblValorMaximo2;
    private javax.swing.JLabel lblValorMinimo;
    private javax.swing.JLabel lblValorMinimo1;
    private javax.swing.JLabel lblValorMinimo2;
    private javax.swing.JLabel lblValormedio;
    private javax.swing.JLabel lblValormedio1;
    private javax.swing.JLabel lblValormedio2;
    private javax.swing.JLabel lblmaximo;
    private javax.swing.JLabel lblmaximo1;
    private javax.swing.JLabel lblmaximo3;
    private javax.swing.JLabel lblmedia;
    private javax.swing.JLabel lblmedia1;
    private javax.swing.JLabel lblmedia3;
    private javax.swing.JLabel lblminimo;
    private javax.swing.JLabel lblminimo1;
    private javax.swing.JLabel lblminimo3;
    private javax.swing.JProgressBar pgbPrimeira;
    private javax.swing.JProgressBar pgbSegunda;
    private javax.swing.JProgressBar pgbTerceira;
    // End of variables declaration//GEN-END:variables
}
